package com.craftfest.blocks.valentines;

import java.util.Random;

import net.minecraft.block.BlockLeaves;
import net.minecraft.block.material.Material;
import net.minecraft.creativetab.CreativeTabs;
import net.minecraft.init.Blocks;
import net.minecraft.item.Item;
import net.minecraft.util.IIcon;

import com.craftfest.CraftFestMod;

public class CherryBlossomLeaves extends BlockLeaves{
	
	public CherryBlossomLeaves(){
		super();
		setBlockName("cherryblossomleaves");
		setBlockTextureName(CraftFestMod.MODID + ":" + getUnlocalizedName().substring(5));
		setCreativeTab(CraftFestMod.tabSpring);

	}
	
	//autogenerated method
	@Override
	public IIcon getIcon(int p_149691_1_, int p_149691_2_) {
		
		return null;
	}

	//autogenerated method
	@Override
	public String[] func_150125_e() {
		
		return null;
	}
	
    public Item getItemDropped(int p_149650_1_, Random p_149650_2_, int p_149650_3_)
    {
    	//TODO: add cherry blossom sapling
        return Item.getItemFromBlock(Blocks.sapling);
    }
	

}
